name: Deploy RunPod Frontend React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: anamika8/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: |
          echo "REACT_APP_API_KEY=${{ secrets.RUNPOD_API_KEY }}" >> $GITHUB_ENV
          npm run build

      - name: Deploy to GitHub Pages
        uses: anamika8/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build