name: Deploy RunPod Frontend React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Store Secrets in .env file
        run: echo "REACT_APP_API_KEY=${{ secrets.RUNPOD_API_KEY }}" >> .env

      - name: Build the app
        run: |
          echo "REACT_APP_API_KEY=${{ secrets.RUNPOD_API_KEY }}" >> $GITHUB_ENV
          ESLINT_NO_DEV_ERRORS=true CI=false npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build